// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpdRR9QA84a1dRk_w_xfzztbkD3O06nkg',
    appId: '1:1011426448213:web:f0080fd1de928050d415dc',
    messagingSenderId: '1011426448213',
    projectId: 'evoting-app-2c8fd',
    authDomain: 'evoting-app-2c8fd.firebaseapp.com',
    storageBucket: 'evoting-app-2c8fd.appspot.com',
    measurementId: 'G-CJYL7X934Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxlRT15YS4hjGgRmJWwUo4Nhw3BqMxlO0',
    appId: '1:1011426448213:android:6ada925bf03baf06d415dc',
    messagingSenderId: '1011426448213',
    projectId: 'evoting-app-2c8fd',
    storageBucket: 'evoting-app-2c8fd.appspot.com',
  );
}
